// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.DbConTexts;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(HocVienDbContext))]
    partial class HocVienDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Entites.HocVien", b =>
                {
                    b.Property<int>("MaHV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<int?>("LopMaLop")
                        .HasColumnType("int");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.HasKey("MaHV");

                    b.HasIndex("LopMaLop");

                    b.ToTable("HocViens");

                    b.HasData(
                        new
                        {
                            MaHV = 1,
                            Email = "NguynA@gmail.com",
                            GioiTinh = true,
                            HoVaTen = "Nguyễn Văn A",
                            MaLop = 1,
                            NgaySinh = new DateTime(2000, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaHV = 2,
                            Email = "NguynB@gmail.com",
                            GioiTinh = true,
                            HoVaTen = "Nguyễn Văn B",
                            MaLop = 2,
                            NgaySinh = new DateTime(2001, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaHV = 3,
                            Email = "NguynC@gmail.com",
                            GioiTinh = true,
                            HoVaTen = "Nguyễn Văn c",
                            MaLop = 1,
                            NgaySinh = new DateTime(2001, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaHV = 4,
                            Email = "NguynD@gmail.com",
                            GioiTinh = true,
                            HoVaTen = "Nguyễn Văn D",
                            MaLop = 2,
                            NgaySinh = new DateTime(2001, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebApplication1.Entites.Lop", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.HasKey("MaLop");

                    b.ToTable("Lops");

                    b.HasData(
                        new
                        {
                            MaLop = 1,
                            TenLop = "Tiếng Anh Cơ bản"
                        },
                        new
                        {
                            MaLop = 2,
                            TenLop = "Tiếng Anh Nâng Cao"
                        });
                });

            modelBuilder.Entity("WebApplication1.Entites.HocVien", b =>
                {
                    b.HasOne("WebApplication1.Entites.Lop", "Lop")
                        .WithMany("HocViens")
                        .HasForeignKey("LopMaLop");
                });
#pragma warning restore 612, 618
        }
    }
}
